### ISSUE TITLE
Make CheckEnvoyStart optional

### ISSUE THREAD

**Issue by yteraoka** [maksim-paskal/envoy-sidecar-helper#4]
Hi,

Thank you, this is what I was looking for.
I would like to use this with Istio.
Istio has its own mechanism (`holdApplicationUntilProxyStarts`)  for waiting for envoy to start. So it would be helpful if the wait handling of envoy-saidecar-helper is optional.
This would eliminate the need for volume mounts.

**Comment by maksim-paskal** [comment]
@yteraoka thanks for feedback, sounds great, fix this tomorrow

**Comment by maksim-paskal** [comment]
@yteraoka now you can disable envoy sidecar ready check with this specs

```yaml
- name: envoy-sidecar-helper
  image: paskalmaksim/envoy-sidecar-helper:latest
  imagePullPolicy: Always
  args: 
  - -envoy.ready.check=false
  - -envoy.port=9901
```
