### ISSUE TITLE
Question: How does the envoy-sidecar-helper shut down?

### ISSUE THREAD

**Issue by johnynfulleffect** [maksim-paskal/envoy-sidecar-helper#8]
Using this as a sidecar, to shut down the istio sidecar, how does this sidecar shut down?  upon successful shutdown of istio?

**Comment by maksim-paskal** [comment]
This sidecar will shutdown when your first container in pod shutdown.

Helper by default will watch first container status of his pod, and when first container status become `Terminated`, helper will send http request to shutdown envoy sidecar, and than will be succesfully shutdown by itself.

Admin port of envoy sidecar in Istio works on 15000 port. To stop istio envoy sidecar and this helper - you need to add to your pod serviceAccount with pods view permissions, and this helper sidecar.

```yaml
serviceAccount: envoy-sidecar-helper
...
- name: envoy-sidecar-helper
  image: paskalmaksim/envoy-sidecar-helper:latest
  imagePullPolicy: Always
  args:
  - -envoy.port=15000
  env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
```

**Comment by johnynfulleffect** [comment]
Thank you @maksim-paskal !

Follow-up question regarding permissions.  I added the following to `mynamespace`:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-sidecar-helper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy-sidecar-helper-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-sidecar-helper
roleRef:
  kind: Role
  name: envoy-sidecar-helper-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-sidecar-helper
  namespace: default
```

However, I am still seeing this log in the envoy-sidecar-helper pod:

`{"error":"error getting pod: pods \"mypod-zkjr5\" is forbidden: User \"system:serviceaccount:mynamespace:default\" cannot get resource \"pods\" in API group \"\" in the namespace \"mynamespace\"","file":"github.com/maksim-paskal/envoy-sidecar-helper/pkg/api/api.go:134","func":"github.com/maksim-paskal/envoy-sidecar-helper/pkg/api.CheckContainerStop","level":"error","msg":"","time":"2022-09-20T17:19:11Z"}`

**Comment by maksim-paskal** [comment]
try to change `RoleBinding` subject to service account in your namespace
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-sidecar-helper
roleRef:
  kind: Role
  name: envoy-sidecar-helper-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-sidecar-helper
  namespace: mynamespace
```

**Comment by johnynfulleffect** [comment]
> 

Yeah, thanks!  I tried that, still seeing the issue.  

```yaml
Name:         envoy-sidecar-helper
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  Role
  Name:  envoy-sidecar-helper-role
Subjects:
  Kind            Name                  Namespace
  ----            ----                  ---------
  ServiceAccount  envoy-sidecar-helper  mynamespace
```

**Comment by johnynfulleffect** [comment]
I think perhaps I am not associating the service account to the pod.

**Comment by maksim-paskal** [comment]
It's can be a reason, to figure out I need your kubernetes version, and your pod Yaml

**Comment by johnynfulleffect** [comment]
The change I needed was to use the service account `envoy-sidecar-helper` instead of `default`.  In order to do this, only for the envoy-sidecar-helper pod was a bit tedious.  I had to use the ServiceAccount token secret and mount that into the container:

```yaml
  volumeMounts:
  - name: envoy-sidecar-helper
    mountPath: /var/run/secrets/kubernetes.io/serviceaccount
volumes:
- name: envoy-sidecar-helper
  secret:
    secretName: envoy-sidecar-helper-token-xg5d2
```

This is not ideal.  Still figuring out the best solution to this.
